### ISSUE TITLE
Регистрация и аутентификация пользователей

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#1]
В проект нужно добавить:
- аутентификацию по логину и паролю;
- регистрацию пользователя.

**Comment by ASbeletsky** [comment]
В качестве механизма аутентификации предлагаю использовать куки-аутентификацию, с помощью [ASP.NET Core Identity](https://metanit.com/sharp/aspnet5/16.1.php).

План реализации(пример реализации есть [тут](https://metanit.com/sharp/aspnet5/16.2.php)):

1. Создать модель пользователя User;
2. [Добавить ее в dbcontext](https://metanit.com/sharp/aspnet5/16.2.php);
3. Создать User repository и добавить в его в Unit of work; (опционально) (инфрастуруктура для этого реализована в [этой задаче](https://github.com/ASbeletsky/LMS/issues/14)). Для реализации методов репозитория использовать [UserManager класс](https://metanit.com/sharp/aspnet5/16.7.php);
4. Создать [модели представления](https://metanit.com/sharp/aspnet5/8.2.php) для аутентификации и регистрации пользователя;
5. Создать AccountContoller c методами для [аутентификации](https://metanit.com/sharp/aspnet5/16.4.php) и [регистрации](https://metanit.com/sharp/aspnet5/16.3.php); 
6. Добавить [валидацию] (https://metanit.com/sharp/aspnet5/16.10.php)при регистрации пользователя (опционально).

**Comment by MindForks** [comment]
Возможно имеет смысл опустить слой LMS.Identity, т.к. UserRepository предварительно создавался в Date.
Как шаблон формы регистрации использую SB Admin Bootstrap. Который доработаю до нужного вида, добавив дополнительные поля вида: Образование, Места работы и тд.

План по регистрации:
1. Создать RegisterViewModel.
2. Реализовать UserViewController, для взаимодействия с моделью
3. далее по плану выше

**Comment by ASbeletsky** [comment]
LMS.Identity нужен и будет зареюзан проекте LMS.Client.Web.  

> дополнительные поля вида: Образование, Места работы и тд.

их добавлять не нужно на форму. Для этого будет отдельная задача, возможно будет реализовано в рамках задачи #3.

> Реализовать UserViewController, для взаимодействия с моделью
Лучше это все делать в AccountContoller.

**Comment by MindForks** [comment]
Оставшееся время реализации 2-4 часа.

**Comment by ASbeletsky** [comment]
Нет, на это отдельная задача - #3 , напиши в комментариях к этой задаче какой функционал по твоему должен быть по управлению пользовательскими профилями.

**Comment by ASbeletsky** [comment]
Задача сделана не по требованиям. Вместо аутентификации по логину и паролю была сделана аутентификация по электронной почте и паролю. Необходимо заменить Email на User Name. Поле Email должно быть не обязательным для заполнения, а UserName должно быть обязательным.
