### ISSUE TITLE
Просмотр результатов тестирования

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#11]
**User story**: Студенты проходят тестирование в компании, путем ответа на воросы или решение задач, для подтверждение своих знаний и навыков. Необходимо автоматизировать этот процесс.

**Use case**: Reviewer LMS просматривает результаты тестирования.

_When_: Reviewer заходит на страницу с расписанием тестовых сессий и выбирает состоявшуюся сессию.
_Then_: Открывается страница с информацией о сессии Session Details  (existing #41 ).
**Requirements**: Добавить на страницу Session Details кпопку View Results

_When_: Reviewer нажимает на кнопку View Results
_Then_: Открывается страница с результатами тестирования все участников сессии. Содержит таблицу с аттрибутами:

- Examinee - имя участника
- Test title - название теста который проходил Examinee 
- Test duration - реальное время затраченое на прохождение теста
- Score - итоговое колличество баллов
- Actions - кнопка details

_When_: Reviewer нажимает на кнопку details
_Then_: Открывается страница с результатами тестирования конкретного участника. Содержит все вопросы теста с ответами учасника. Правильный ответ (если он есть в системе) отмечается зеленым цветом, не правильный - крассным.

**Comment by Tirraon** [comment]
1. На данный момент при нажатии на событие в календаре сессий открывается его редактирование.
Есть смысл смотреть на дату начала сессии:
- если она прошла - открывать Details
- если она не прошла - открывать Edit
2. Нужно ли в списке ответов выводить инфо о вопросе? Content...
3. У нас правильность ответа задается Score (например 0-10, в разных тасках по разному). Можно сделать не красный-зеленый, а красный (0-25% от максимума), желтый (25-75%) и зеленый (75-100%). И дополнительно в списке отображать реальное число.

План:
- [ ] Дождаться #59 
- [ ] ExameneeResultDTO + Mapping (от TestSessionUser) : TestTitle, UserName, UserId, Duration, Score, Test+Id
- [ ] Добавить в TestSessionDTO 
- ExameneeResultDTO
- [ ] TestSessionRepository должен Include(TestSessionUser)
- [ ] TestSessionService.GetById:
- проставлять Test в TestSessionUser из уже известного списка TestSession.Tests (чтобы не нужно было добавлять ThenInclude для каждого TestSessionUser)
-  считать Score как сумму Answer.Score (Answer отдельно вытаскивать по TestSessionUserId, если их не будет в этой сущности)
- [ ] TestSessionControler.Details (id)
- [ ] TestSession/Details view

**Comment by Tirraon** [comment]
Каким образом тогда определять, правильный ли ответ? Только если наьрал
