### ISSUE TITLE
Базовая архитектура проекта

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#13]
Необходимо настроить рабочую среду для проекта:
- выделить основные архитектурные слои;
- интерфейсы, через которые слои будут взаимодействовать;
- добавить слой для юнит-тестирования;
- создать/проинициализировать файлы конфигурации;
- настроить деплой.

**Comment by ASbeletsky** [comment]
В качестве архитектуры для данного проекта предлагаю использовать [многоуровневую архитектуру](https://metanit.com/sharp/mvc5/23.5.php). 
Кроме стандартных 3 уровней (data, business, presentation ) можно добавить уровень для абстракций, в котором определить основные интерфейсы, через которые другие уровни будут общаться друг с другом. Реализация интерфейсов будет в 3 основных уровнях. 
Опционально можно добавить вспомогательный слой, где объявить зависимости проекта, для использования [dependency inversion](https://metanit.com/sharp/mvc5/21.1.php) 

План реализации:

1. Создать visual studio soution - LMS.Admin.sln
2. Добавить проекты 
LMS.Data - data access layer
LMS.Business - business layer
LMS.Admin.Web - presentation layer
LMS.Interfaces - слой абстракций (опционально)
LMS.Bootstap - вспомогательный слой для dependency inversion (опционально)
LMS.Test - слой для тестов
3. Проинициализировать .gitignore для работы в среде с# и visual studio
4. [Настроить развертывание на iis через файловую систему](https://metanit.com/sharp/mvc/13.2.php) (опционально)

**Comment by Tirraon** [comment]
Остался только вопрос деплоя?
Или в этой задаче еще что-то нужно?

**Comment by ASbeletsky** [comment]
Задача выполена, на деплой на удаленный хостинг будет отдельная задача позже.
