### ISSUE TITLE
Инфраструктура Data Layer

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#14]
В проекте нужно LMS.Data организовать доступ к базе данных. 
Необходимо:

- определиться с базой данных;
- добавить подходящую ORM;
- создать интерфейсы для работы с данными.

**Comment by ASbeletsky** [comment]
В качестве базы я бы выбрал одну из бесплатных реляционных баз данных ([MySql](https://ru.wikipedia.org/wiki/MySQL), [PostgreSql](https://ru.wikipedia.org/wiki/PostgreSQL)).  
Из ORM можно рассмотреть варианты с [entity framework](https://metanit.com/sharp/entityframework/) и [dapper](https://metanit.com/sharp/articles/mvc/dapper.php).

Что касается интерфейса для работы с базой советую почитать [это](https://metanit.com/sharp/mvc5/23.7.php). Тут используются 2 популярных шаблона - [repository](https://metanit.com/sharp/articles/mvc/11.php) и [unit of work](https://metanit.com/sharp/mvc5/23.3.php).
**Как определись с тем что использовать, напишите план реализации в комментарии** (пример плана есть [тут](https://github.com/ASbeletsky/LMS/issues/13)).

**Comment by Tirraon** [comment]
1. Будем использовать MySQL Community Server и EF
2. Установить БД
3. Добавить необходимый ConnectionString
4. Создать наследника DbContext - LMSDbContext
5. Интерфейсы IRepository, IUnitOfWork
6. Реализация IUnitOfWork - EntityFrameworkUnitOfWork, которая принимает LMSDbContext как зависимость
7. Папки Entities и Repositories для будущих сущностей

Была создана ветка feature-14 с начальной работой

**Comment by ASbeletsky** [comment]
Задача выполнена.

**Comment by ASbeletsky** [comment]
Нужно добавить поддержку асинхронных репозиториев:

- добавить интерфейс IRepositoryAsync;
- создать Generic Repository, который реализует IRepositoryAsync

**Comment by ASbeletsky** [comment]
Оставить старый, добавить IRepositoryAsync, с такими же мотодами как в IRepository, только асинхроннымы.
