### ISSUE TITLE
Инициализация сессии для прохождения тестов

### ISSUE THREAD

**Issue by inqueez** [ASbeletsky/LMS#19]
При нажатии на кнопку Start/Начать:

- получить список вопросов
- запустить таймер

Необходима поддержка восстановления сессии, на случай если по какой либо причине пользователь
получил ошибку с сервера или перезагрузил страницу, сессия оборвалась

**Comment by Olexseenko** [comment]
Поскольку сессии не предназначены для хранения долго существующей информации и при открытии другой вкладки будет создана отдельная сессия не имеющая связей с предыдущей. Для хранения ответов будем использовать таблицу на стороне сервера определяя необходимые ответы по Id пользователя, а на стороне клиента переменные в sessionStore для отслеживания изменений ответов (что бы не обращаться к бд лишний раз).
Поскольку есть 3 вида ответов для избежания разветвления на несколько таблиц все ответы будут храниться как сериализации по соответствующим типам в формате Json.
Таблица Answer:
- Id
- TestId
- TaskId
- сохранённый Json
