### ISSUE TITLE
Авторизация, добавление ролей и разграничение доступа

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#2]
**Motivation**: Пользователи системы работают с определенным функционалом LMS, согласно их потребностям, а не со всем функционалом целиком. Кроме того, некоторые функции системы не должны быть доступны для общего использования. 

**User story**: Пользователь после аутентификиции проходит авторизацию его профиля в системе, тем самым получая доступ к необходимым ему функциям, согласно его роли.

**Requirements**:

- Добавить авторизацию пользователя согласно его роли;
- Создать зарезервированную роли в системе - admin, moderator, reviewer, examinee;
- Создать системного пользователя в роли Admin (login admin, password - apriorit);
- Только для пользователей в роли Admin разрешить регистрацию других пользователей (задача #1);
- На форму регистрации добавить обязательное  поле Role - выпадающий список с доступными ролями системы.

**Comment by ASbeletsky** [comment]
Я добавил описание задачи. @MindForks распиши план подробнее, в каком слое какие модели/сервисы ты будешь добавлять. Какие методы будут и что они будут делать. После составление плана напиши эстимейт по задаче, с учетом рисков.

**Comment by MindForks** [comment]
Вопрос по /авторизации пользователя согласно его роли/. 
У нас будет одна форма для входа по результатам которой перенаправит в админку или на тестирование, или же две разных ?

Вопрос по / менеджмент ролей (создание, редактирование, удаление)/. 
Я не очень понимаю для чего это может быть удобно, возможно стоит создать 3 зарезервированные роли, по типу(admin/user/moderator).

**Comment by ASbeletsky** [comment]
> У нас будет одна форма для входа по результатам которой перенаправит в админку или на тестирование, или же две разных ?
Будет 2 разных формы авторизации. Форма для клиентского логина будет сделана в задаче #22 

> Я не очень понимаю для чего это может быть удобно, возможно стоит создать 3 зарезервированные роли, по типу(admin/user/moderator).
Ладно, согласен, создай тогда зарезирвированные роли  admin, moderator, reviewer, examinee

**Comment by MindForks** [comment]
Возникла необходимость разрешать доступ к регистрации не всем, стоит ли разбивать AccountController на RegisterController + LoginController, для того, что бы этим класса по отдельности добавить атрибут доступа по ролям ?

**Comment by MindForks** [comment]
Регистрация реализована через email адрес, поэтому возникают сложности при создании зарезервировано admin с логином "admin".  Могу ли я использовать admin@gmail.com в качестве логина для админа ?

**Comment by ASbeletsky** [comment]
> Возникла необходимость разрешать доступ к регистрации не всем, стоит ли разбивать AccountController на RegisterController + LoginController, для того, что бы этим классам по отдельности добавить атрибут доступа по ролям и не писать атрибуты над методами ?

Нет, разграничивать доступ в рамках методов контроллера - норамальная практика

**Comment by ASbeletsky** [comment]
> Регистрация реализована через email адрес, поэтому возникают сложности при создании зарезервировано admin с логином "admin". Могу ли я использовать admin@gmail.com в качестве логина для админа ?

Нет, в задаче #1  сказано было что для аутентификации - логин и пароль. Сделал через имейл - теперь придется переделывать в рамках задачи #1 .

**Comment by MindForks** [comment]
/Добавить авторизацию пользователя согласно его роли; //
1. Пользователя с ролью examinee в admin впускать не будет, а выдавать сообщение о том, что у него недостаточно доступа.
2.Во всех остальных случаях все попадают в admin где они видят все пункты но при нажатии на register(к примеру) сообщение об отсутствии прав ? Или же мы отображаем изначально доступные(по роли) пункты меню ?
3.

**Comment by ASbeletsky** [comment]
> мы отображаем изначально доступные(по роли) пункты меню ?

@MindForks  admin, moderator могут добавлять/редактирвать/удалять задания и категории заданий, а reviewer может только просматривать их
