### ISSUE TITLE
Логин пользователя, который будет проходить тест, по коду

### ISSUE THREAD

**Issue by inqueez** [ASbeletsky/LMS#22]
На старте тестовой сессии нужно добавить аутентификацию пользователя в роли Examinee в систему. Пользователь аутентифицируется по 8-значному коду, который уникально идентифицирует Examinee в рамках конкретной сессии. Пример кода - "abcd1234". Examinee имеет право войти в систему только в течении запланированной тестовой сессии (#41 ) +- 15 минут.

**Comment by ASbeletsky** [comment]
Сам код хранить в таблице TestSessionUser, и заполнять при создании тест сессии (#41 )

**Comment by Megaremzik** [comment]
План

- [ ] Добавить в таблицу TestSessionUser столбец Code

- [ ] Добавить метод генерации кодов

- [ ] Добавить заполнение кодов с проверкой на уникальность.

- [ ] Добавить контроллер AuthorizationController в проекте LMS.Client.Web

- [ ] Добавить LoginViewModel в проекте LMS.Client.Web

- [ ] Добавить представление Login.cshtml

- [ ] Добавить метод  в IdentityService LoginUser, который принимает код как параметр.
