### ISSUE TITLE
Поддержка рисования диаграмм для вопросов такого типа

### ISSUE THREAD

**Issue by inqueez** [ASbeletsky/LMS#23]
Найти и применить плагин, который позволяет рисовать диаграммы или хотябы что-то типа Paint

**Comment by Tirraon** [comment]
https://github.com/ASbeletsky/LMS/issues/5#issuecomment-403849834

Для диаграмм выглядит относительно удобным tui.editor.
Однако его проблема - все нужно расписывать руками в markdown.
Но для вертикальных гистограм есть возможность копировать таблицы из экселя - они подхватываются.
Если копировать сами диаграммы с экселя, то они вставляются как изображения в формате base64 (может быть удобно, но, наверно, не в этом случае)

Пример:
https://nhnent.github.io/tui.editor/api/latest/tutorial-example11-chart.html
