### ISSUE TITLE
Интерактивный список текущих сессий

### ISSUE THREAD

**Issue by Tirraon** [ASbeletsky/LMS#29]
В админке была бы удобна страница со списком текущих сессий, который отображает информацию об их статусе:
- время старта
- потраченное время
- решенные вопросы
- …

Информация может динамически обновляться по веб сокетам.

Функционал может быть отложен до последнего как опциональный.

**Comment by Olexseenko** [comment]
Можно в SignalR создать группу User и Admins при этом у админов будет метод который будет обращаться к группе User и по ней строить таблицу со всеми пользователями и столбцами под данные о них, при этом будет ещё другой метод который по таймеру будет отправлять данные о пользователях админам которые по этим данным будут заполнять столбцы. Так же при добавлении новых пользователей админам будут отсылаться данные для расширения таблицы или свёртывания уже не существующих строк.
