### ISSUE TITLE
Управление профилем пользователя

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#3]

**Comment by MindForks** [comment]
Отображается список пользователей(сортировка по дате активности)
Функционал по управлению профилем:
1. Изменение прав доступа(admin/user/moderator)
2. Удаление профиля
3. Изменение уровня(junior/middle/senior)

**Comment by ASbeletsky** [comment]
Для пользователя в роли Examinee нужно добавить информацию:
ФИО, Год рождения, Вуз, Факультет, Специальность, Курсе, Уровень английского языка, Номер телефона, E-mail, Доп.информация

**Comment by MindForks** [comment]
Я вижу это так: есть вкладка Users в боковом меню. По нажатию отображаю таблицу(список всех пользователей) колонки: Username, Role, Actions. У Actions есть 3 действия: edit, delete, test.
edit - возможность изменить role, password, username и все остальные поля.
delete - удаление
test - redirect  на пройденные тесты с результатами.

План работы:
1. Изменение модели, формы, добавление новых полей. При регистрации в другой роле, поля в бд будут пустыми.
2. UsersController, с методами Edit and Delete and View
3. Создание view Users в папке Account

**Comment by MindForks** [comment]
новые поля User:
Comment, EnglishLevel, Course, Specialty, Faculty, College, Year. Вопрос ФИО актуальный

**Comment by ASbeletsky** [comment]
@MindForks 
> test - redirect на пройденные тесты с результатами.

Это пока не нужно.

> новые поля User:
> Comment, EnglishLevel, Course, Specialty, Faculty, College, Year.

Вынеси в отдельную таблицу - Examinee с ссылкоq на UserId

> Вопрос ФИО актуальный

можешь оставить first, last name
