### ISSUE TITLE
Инфраструктура для миграций базы данных

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#30]
Необходимо настроить инфраструктуру для миграций Entity Framework Core для MySql.
Добавить описание как работать с миграциями в комментарии к задаче.

**Comment by Tirraon** [comment]
Через пол часа отправлю PR

**Comment by Tirraon** [comment]
Для создания новой миграции после обновления модели нужно выполнить команду:
_dotnet ef migrations add **ИМЯ_МИГРАЦИИ** -p LMS.Data -s LMS.Admin.Web_

Для обновления базы данных на основе локальных миграций:
_dotnet ef database update -p LMS.Data -s LMS.Admin.Web_

Выполнять команды нужно и корневой папке решения.
Вместо **ИМЯ_МИГРАЦИИ** писать имя миграции, которое отображает суть изменений моделей.

**Comment by MindForks** [comment]
Для миграции через package manager

Add-Migration **ИМЯМИГРАЦИИ**-Project LMS.Data -startupproject LMS.Admin.Web
Update-Database -Project LMS.Data -startupproject LMS.Admin.Web
