### ISSUE TITLE
Создание категории для вопросов

### ISSUE THREAD

**Issue by inqueez** [ASbeletsky/LMS#32]
Use case: Администратор LMS создает категорию для вопросов, которую в момент создания самого вопроса, будет возможность выбрать

> When: Администратор заходит на страницу со списком категорий вопросов
> Then: Категории представленны в виде таблицы с колонками:
> Title - название категории
> Count - количество вопросов в данной категории
> Actions: Edit, Delete

> When: Администратор нажимает на кпопку Create или Edit
> Then: Отрывается страница с формой для создания новой категории. Форма содержит поля:
> Title - название категории

> When: Администратор нажимает на кпопку Delete
> Then: Появляется всплывающие окно с текстом "Are you sure that you want to delete this category?" с опциями Yes, No. Если администратор выбирает Yes, тогда категория удаляется (вопросам которые были связаны с этой категорией устанавливается ключ на категорию в значение NULL), иначе всплывающие окно закрывается.

**Comment by inqueez** [comment]
Ребята, я еще не в курсе ваших логинов в GitHub, эту задачу будет делать Акименко Максим. Максим, переведи на себя задачу.

**Comment by Tirraon** [comment]
- [ ] Создать новую ветку feature-32 на основе development или обновить уже созданную, вытащив последние изменения из development
- [x] Создать сущность Category в LMS.Entites с полями Id, Title
- [x] Использовать BasicRepository для сущностей Category, добавив его в IUnitOfWork
- [ ] Создать dto-объект CategoryDTO в LMS.Dto с полями Id, Title, TasksCount (нужно добавить TasksCount к уже готовому объекту)
- [x] Зарегистрировать в LMS.Bootstrap маппинги для Category <-> CategoryDTO
- [ ] Создать CategoryService в LMS.Business / Services, наследовать от BaseService с методами:
- DeleteAsync (id), использующий Delete репозитория категорий через unitOfWork (поле из родительского BaseService), после чего вызывающий SaveAsync в unitOfWork
- CreateAsync (CategoryDTO) с помощью mapper (поле из родительского BaseService) конвертирует аргумент в тип Category и через репозиторий добавляет его, после чего вызывает SaveAsync
- UpdateAsync (CategoryDTO) с помощью mapper (поле из родительского BaseService) конвертирует аргумент в тип Category и через репозиторий обновляет его, после чего вызывает SaveAsync. Так же нужно предусмотреть сценарий, когда объект отсутствует в репозитории: проверять с помощью Get (id); при отсутствии создавать новый, а не обновлять несуществующий.
- GetAll должен из репозитория вытаскивать сущности, конвертировать каждую mapper`ом в CategoryDTO. В поле TasksCount каждой внести значение полученное из unitOfWork.Tasks.Filter, сравнивая по CategoryId.
- [ ] Написать тесты в LMS.Test / Services / CategoryServiceTests:
- Проверка DeleteAsync - было ли удаление из репозитория с сохранением через IUnitOfWork
- Проверка UpdateAsync - было ли обновление категории в репозитории с сохранением
- Проверка UpdateAsync с новой категорией - было ли создание категории в репозитории с сохранением
- Проверка CreateAsync - было ли создание новой категории в репозитории с сохранением
- Проверка GetAll с добавлением с проверкой TasksCount, в моке репозитория заполнять тестовыми данными
- [ ] Создать CategoryController в LMS.Admin.Web / Controllers, передав через конструктор CategoryService, с методами:
- [HttpGet] List () - вывод всех элементов
- [HttpGet] Edit (id) - отображение страницы с возможностью редактирования 
- [HttpPost] Edit (CategoryDTO) - применение изменений
- [HttpGet] Create () - отображение страницы с возможностью создания новой категории
- [HttpPost] Create (CategoryDTO) - применение создания 
- [HttpPost] Delete (id) - удаление
- [ ] Создать вью List - вывод списка элементов, с ссылками на Edit (id) и на открытие диалогового окна подтверждения удаления через Delete (id)
- [ ] Создать вью Edit - страница, на которой можно редактировать единственное поле - Title, и кнопка "Save" (вызывает через форму Edit (CategoryDTO) )
- [ ] Создать вью Create - страница, на которой можно создать категорию с единственным полем - Title, и кнопка "Save" (вызывает через форму Edit (CategoryDTO) )
- [ ] Добавить в _Layout новые MenuItemViewModel для создания новой категории и открытия списка созданных

Вышеперечисленные View создаются в каталоге Views/Category на основе автоматической генерации View, которые после под задачи подстраиваются
