### ISSUE TITLE
Деплой Admin.Web на удаленный хостинг

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#38]
**TODO:**

- развернуть приложение LMS.Admin.Web на удаленный хостинг;
- сконфигурировать приложение для работы с MySql бозой на Azure;
- добавить интеграцию с github, что бы деплоилась версия из ветки develop после изменений в ней (CI).

После окончании работы в комментариях указать url приложения на хостинге.

**Comment by MindForks** [comment]
Моя пробная лицензия на Azure закончилась на выходных, поэтому больше нет возможности его использовать для реализации задачи.
Варианты решения:
1. Пробовать использовать Amazon, но там снова нужны данные карты и т.д.
2. Договориться с сис. админом за локальный сервер.
3. Использовать другой хостинг для развертывания приложения, но все проанализированные(которые поддерживают Core и MySQL) требуют подписки с первого месяца, к примеру (Parking.ru, Infobox, Smarterasp.net).

**Comment by Tirraon** [comment]
https://www.freemysqlhosting.net/

**Comment by MindForks** [comment]
В качестве БД использую бесплатный аккаунт. https://www.db4free.net/.
Данные для подключения: 
"DefaultConnection": "server=db4free.net;UserId=apriorit;Password=Password1;database=lmsapriorit;"

**Comment by ASbeletsky** [comment]
@MindForks @Tirraon  что на счет деплоя веб проложения? получиться настроить через Azure? Если да, @Tirraon забирай задачу, задеплошь у себя на аккаунте.

**Comment by MindForks** [comment]
В LMS Admin можно попасть по ссылке 
https://lms-apriorit.azurewebsites.net/

**Comment by ASbeletsky** [comment]
Почему там нет стилей?

**Comment by MindForks** [comment]
@ASbeletsky потому что нужно было сконфигурировать gitignore + appsettings + bundleconfig. После того как эта ветка попадет в dev все должно появиться, а на данный момент в dev это выглядит так как по ссылке https://lms-apriorit.azurewebsites.net/
