### ISSUE TITLE
Создание тестовых заданий

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#4]
**User story**: Студенты проходят тестирование в компании, путем ответа на воросы или решение задач, для подтверждение своих знаний и навыков. Необходимо автоматизировать этот процесс.

**Use case**: Администратор/Модератор LMS создает задания для тестирования студентов в ввиде теста с вариантами ответа.

**Navigation**: Tasks -> Create/Edit

**Requirements**: 

1. Добавить в поле Type новую опцию - "question with options"

2. When: Администратор/Модератор выбирает значение "question with options" в поле Type
Then: Под полем Content появляется поле Options Count - numeric input 

3. When: Администратор/Модератор меняет значение в Options Count
Then: Под полем Content появляется список вариантов ответа в колличестве Options Count  формата:

Answer | Label | text | 
-------- | ------ | ------ |
[radio button] | [ label with value a/b/c ... /z] | [text input]

**Comment by MindForks** [comment]
По-поводу отдельного label со значениями a,b,c... Может его не стоит создавать ? А генерировать эти символы. Таким образом мы получим возможность перемешивать вопросы.
Для хранения вариантов ответов на вопросы с выбором я думаю стоит создать отдельную таблицу optiontasks, которая будет ссылаться на существующую, а собственно сам вопрос хранить в существующей таблице.

**Comment by ASbeletsky** [comment]
Label - это чисто на UI, в базе он не обязательный. Распиши план по задаче в комментах

**Comment by MindForks** [comment]
План реализации:
1.В файле LMSDbContext проверяю существуют ли у нас все необходимые TaskType.(для этого создаю миграцию). Использую  builder.HasData
2.В Entities создаю OptionAnswer единицы которого будут вариантом ответа. Имеет Id,TaskId,Content, IsCorrect.
Так же в Entities  OptionsTask : Task. В котором содержится список OptionAnswer и OptionsCount, все остальное от базового класса.
3. В DTO делаю модели.
4. Добавляю View/Task/CreateOption

**Comment by ASbeletsky** [comment]
> В Entities создаю OptionAnswer

Назови лучше TaskAnswerOption.

> Так же в Entities OptionsTask : Task. В котором содержится список OptionAnswer и OptionsCount, все остальное от базового класса.

думаю можно просто добавить ICollection<TaskAnswerOption> Answers к Task и не заморачиваться с населодованием. OptionsCount нужно только на UI и в модель его добавлять не обязательно. 

> Добавляю View/Task/CreateOption CreateOptionTask или мне создавать в отдельной папке с отдельным контроллером

модифицируй существующий сервис и котороллер по работе с Tasks
