### ISSUE TITLE
Планирование тестовых сессий

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#41]
**User story**: Студенты проходят тестирование в компании, путем ответа на воросы или решение задач, для подтверждение своих знаний и навыков. Необходимо автоматизировать этот процесс.

**Use case**: Модератор LMS планирует расписание тестовых сессий.

When: Модератор заходит на страницу запланированных тестов.
Then: Тестовые сессии представленны в виде календаря.

When: Модератор нажимает на пустую ячейку календаря.
Then: Открывается страница создания новой тестовой сессии, содержит форму с атрибутами:
Title - название сессии
Test Template - выпадающий список с шаблонами тестов
Date - дата проведения
Starts - время начала 
Duration - длительность сессии, по умолчанию = Test Template Duration
Tests - список вариантов теста по выбраному шаблону, dropdown multiselect
Members - список examinee, dropdown multiselect

**Comment by Tirraon** [comment]
- [ ] Entites
- TestSession: Title, StartTime (DateTime, дата с временем начала), Duration
- TestSessionVariant: TestSession+Id, TestVariant+Id
- [ ] DbContext, Init migration
- [ ] TestSessionRepository
- [ ] DTOs:
- TestSessionDTO: Title, StartTime, Duration, Variants (TestVariantDTO)
- [ ] Mapping
- [ ] TestSessionService
- GetAll
- Delete (id)
- Create (TestSessionDTO)
- Update (TestSessionDTO)
- [ ] TestSessionServiceTests
- [ ] TestSessionController
- WIP
- [ ] Views
- WIP

**Comment by Tirraon** [comment]
@ASbeletsky 
Мы при создании сессии выбираем список тестов, которые будут на сессии.
Надо ли Examenee выбирать одну из этих сессий прямо в процессе редактирования сессии?

**Comment by ASbeletsky** [comment]
> Надо ли Examenee выбирать одну из этих сессий прямо в процессе редактирования сессии?

Нет, при старте сессии на клиенте тесты должны случайно распределится между Examinee

**Comment by Tirraon** [comment]
Тогда уберу из Examenee ссылку на Test, так как распределение на клиенте не входит в эту задачу.
