### ISSUE TITLE
Создание открытых вопросов

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#5]
**User story**: Студенты проходят тестирование в компании, путем ответа на воросы или решение задач, для подтверждение своих знаний и навыков. Необходимо автоматизировать этот процесс.

**Use case**: Администратор LMS создает задания для тестирования студентов в ввиде открытого вопроса.
_When_:  Администратор заходит на страницу со списком заданий
_Then_: Задания вредставленны в виде таблицы с колонками:

- Category - область знаний к которой относится вопрос
- Type - тип задания
- Complexity - уровень сложности 
- Content - содержание задания
- Actions: Edit, Delete

_When_:  Администратор нажимает на кпопку Create или Edit
 _Then_: Отрывается страница с формой для создания нового задания. Форма содержит поля:
- Category - выпадающий список со списоком категорий
- Type - выпадающий список с 1 опцией - "open-ended question" 
- Complexity - значение от 1 до 10 в виде dropdown list или slider
- Content - text editor с гибким форматированием.

_When_:  Администратор редактирует содержание вопроса
 _Then_: Создается копия вопроса с обновленным содержимым, оригинальный вопрос помечается как не активный. При этом предусмотренна возможность отследить изменения от оригинальной версии.

_When_:  Администратор нажимает на кпопку Delete
 _Then_: Появляется всплывающие окно с текстом "Are you sure that you want to delete this task?" с опциями Yes, No. Если администратор выбирает Yes, тогда задание удаляется, иначе всплывающие 
окно закрывается.

**Comment by Olexseenko** [comment]
![default](https://user-images.githubusercontent.com/40318818/42514416-0ded0f02-8462-11e8-9b5c-eb9e1673fe20.PNG)
Таблица результаты results:
 - поле результата выполнения
 - ссылка на учасника
 - ссылка на тест
Таблица теста:
 - имя и описание
 - которая состоит из списка заданий (некоторого количества таблиц problems_list)
Таблица списка вопросов:
 - включает вес (максимальное количество балов за правильный ответ)
 - ссылается на таблицу вопроса
Таблица вопроса:
 - содержит сам вопрос в текстовом формате
 - проверки на тип вопроса (1 ответ, N ответов, раскрытый)
 - связана с таблицами вида технологии к которой относится и уровня сложности вопроса
 - связана со списком ответов из которых некоторые правельные
 - если проверяется прогарма то сравниваються ответы полученые после выполнения с правельным
Таблица ответов пользователя:
 - связана с списком вопросов
 - и списком ответов на эти вопросы(выбраные пользователем) при вопросе с расширеным ответом
он сохраняется в базу вместе с оценкой после проверки, тоже самое и с написаной програмой

**Comment by Tirraon** [comment]
Для Content и других аналогичных полей (при их наличии) предлагаю использовать разметку Markdown.
Для отрисовки можно взять [Marked](https://github.com/markedjs/marked)
Для редактирования - [SimpleMDE](https://github.com/sparksuite/simplemde-markdown-editor), который включает в себя тулбар и превью (используя Marked)
Как альтернатива - [tui.editor](https://github.com/nhnent/tui.editor), тоже может быть настроен только на отрисовку, но в данном случае все равно придется таскать весь код и для редактора.
Ожидается, что для клиентов будет легковесный markdown движок.
Однако, SimpleMDE уже два года как заброшен (что не сильно должно мешать на самом деле)

Еще есть вариант использовать [Markdig](https://github.com/lunet-io/markdig) на серверной стороне, который мог бы конвертировать Markdown для передачи в клиентскую часть.

**Comment by Tirraon** [comment]
@Olexseenko начал заниматься моделями.
Я пока что зашел со стороны интерфейса.
Когда с моделями для этой задачи будет завершено, я продолжу с остальным.

**Comment by Tirraon** [comment]
План:
1. Был обновлен Web проект в отдельной ветке, на основе которой будет составляться страница с таблицей.
2. @Olexseenko в ветке feature-5 создал необходимые для этой задачи модели:
- Test
- TestCategory
- TestProblem
- ProblemType
- Choise
3. Предлагаю сделать generic-класс репозитория для большинства моделей, у которых его реализация будет идентичная. Избавляясь этим от дублирования кода. Альтернатива - сделать абстрактный репозиторий, но тут все же нужно будет наследоваться для каждой модели.
4. EF должен использоваться в репозитории для подхватывания связанных моделей (чтобы тест включал список вопросов и т.д.)
5. Добавить репозитории в UnitOfWork
6. Сделать сервис (менеджер? вопрос именования) с минимально необходимым функционалом в бизнес слое.
7. Два контроллера:
- для тестов (включая создание, обновление и удаление)
- для вопросов по конкретному тесту (включая создание, обновление и удаление)
8. Соответствующие контроллерам представления
9. Задачу форматирования вопросов предлагаю вынести в отдельную задачу, так как она одна может быть достаточно объемной. Инструменты для нее предлагал в https://github.com/ASbeletsky/LMS/issues/5#issuecomment-403849834

**Comment by ASbeletsky** [comment]
В данной задаче идет речь только о создании вопросов. Само формирование теста будет в отдельное задаче. В этой ветке модей Test, TestCategory, TestProblem, ProblemType, Choise быть не должно.

**Comment by Tirraon** [comment]
@ASbeletsky в таком случае создание каких моделей конкретно необходимо в этой ветке?
Учитывая, что TestProblem == "Вопрос", а ProblemType == "Тип вопроса".
Возможно стоит подправить именование

**Comment by ASbeletsky** [comment]
Всех необходимых для этой задачи : вопрос, категория, тип нужны точно

**Comment by Tirraon** [comment]
Основу допишу сегодня до двух.
Остальное (скорее всего UI) скорее оставлю как [WIP] пулл реквест и потом (дома/завтра) продолжу.

**Comment by Tirraon** [comment]
@ASbeletsky есть вопрос о сложностях.
Мы обсуждали с вами и @inqueez это, было предложение использовать double для определения веса вопроса. 
Сегодня между собой еще обсудили границы веса - от 0 до 10, но это уже как предложение, я не делал.

В задании же "low, medium, high" - как я понимаю захардкоренные enum.
Мне стоит переделать под enum?

**Comment by Tirraon** [comment]
И в задаче нет слов о тестах.
Стоит написать несколько для QuestionService ?
Как минимум нужно тестировать логику с IsVisible и планируемой ссылкой на предыдущую версию.
Осталоьные методы QuestionService тестировать уже с добавлением пагинации и т.д., но в другой задаче.

**Comment by ASbeletsky** [comment]
@Tirraon  На счет веса я согласен что должен быть double, на счет границ я подумаю. Но это не касаетcя текущей задачи, я опишу все что касается веса в соответствующей задаче. 
По поводу сложности, я думаю что ее как раз нужно хранить в шкале от 0 до 10 и как целое число. На UI ее можно предстать как дропдаун или на slider.
