### ISSUE TITLE
Сериализация форм для тестов

### ISSUE THREAD

**Issue by Megaremzik** [ASbeletsky/LMS#50]
Нужно сделать так, чтоб пользователь при возврате на форму, на которой он уже был, видел изменения, которые он сделал в прошлый раз.

**Comment by Megaremzik** [comment]
@inqueez  как это лучше сделать? Нашёл статейку про работу с TempData https://andrewlock.net/post-redirect-get-using-tempdata-in-asp-net-core/ .
Я пока пробую этот вариант, но честно говоря пока криво получается. Как я понял есть ещё вариант с хранением в бд результата формы. Кароче говоря нужен твой совет каким образом этот таск делать.

**Comment by inqueez** [comment]
@Megaremzik 
Вариантов куча, но главный компонент это сериализация. Можешь взять https://api.jquery.com/serializeArray/ и серилизовать на клиенте, а затем на сервере сохранять эти данные в какую-то колонку в базе (на случай падения сервера и востановления сессии) или же хранить в каком-то Dictionary<>. То что ты нашел (вариант 1) вполне нормальный если едлать все срадствами сервера.
