### ISSUE TITLE
Группировка заданий по вариантам

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#7]
**User story**: Студенты проходят тестирование в компании, путем ответа на воросы или решение задач, для подтверждение своих знаний и навыков. Необходимо автоматизировать этот процесс.

Use case: Модератор LMS создает тест согласно шаблона.

When: Модератор заходит на страницу со списком доступных тестов
Then: тесты представленны в виде таблицы с колонками:

When: Модератор нажимает на копку Create или Edit
Then: Отрывается страница с формой для создания/ редактирования теста. Форма содержит:
Template - выпадающий список с шаблоном теста;

- Name - поле для ввода, по умолчанию <Template Name > variant # <порядковый номер теста с этим шаблоном>;
- Для каждого уровня в шаблоне:
       - загловок "[Template Level Description] - [Template Level Count] tasks."
       - список заданий которые удовлетворяют фильтр (Type, Category, Complexity) для данного уровня c полями Type, Category, Complexity, Content и чекбоксом, который отмечает что данная задача выбрана на данном уровне

**Comment by Tirraon** [comment]
@ASbeletsky @inqueez 
1. Нужно ли выводить в списке колонку с категориями и/или другие, которые желают отдельную DTO?
2. Нужно ли помнить шаблон теста? Если да, то нужно обдумать ситуацию, когда шаблон отредактировали, после чего хотят отредактировать вариант по старому (новому?) шаблону. Если нет, то уровни варианта уже нельзя будет отредактировать (нет ссылки на фильтр).
3. Возможно, запретить менять шаблон после создания варианта, но разрешить менять задачи в пределах уровней шаблона (при изменении варианта после изменений шаблона: если там были удалены уровни - удалить в варианте, если были добавлены - добавить пустые в варианте, если был отредактирован - перепроверить выбранные задачи по новому фильтру).
Еще есть смысл отмечать в списке "грязные" варианты, шаблон которых был изменен, но вариант не был обновлен.
4. Я правильно понимаю систему **ответов**: будет отдельная модель (TestResult ?), которая будет хранить ответы (id вопроса + ответ) и ссылку на вариант? Если так, то можно не волноваться, что вариант изменится после прохождения теста - TestResult будет ссылаться на ответы к старому списку вопросов.

**Comment by Tirraon** [comment]
Предварительный план
- [ ] Entities
- TestVariantLevelTask: TestVariantLevel, Task
- TestVariantLevel: Title, TestTemplateLevelId, Tasks (TestVariantLevelTask)
- TestVariant: Title, TestTemplateId, Level (TestVariantLevel)
- [ ] DTOs
- TestVariantLevelDTO: Title, TestTemplateLevelId, Tasks (TaskDTO), AvailableTasks (TaskDTO), TaskFilterDTO (фильтр для отображения в UI)
- TestVariantDTO: Title, TestTemplateId, Level (TestVariantLevelDTO)
- [ ] TestVariantRepository
- [ ] Mapping 
- [ ] DbContext + Migrations
- [ ] TestVariansService
- GetAll
- Delete (id)
- Create (TestVariantDTO)
- Update (TestVariantDTO) 
- BindToTemplate (TestVariantDTO, TestTemplateId) - обновляет список уровней и остальных полей в соответствии с шаблоном
- [ ] TestVariansServiceTests
- [ ] TestVariantController 
- методы для List, Delete
- методы для Create (templateId? - по умолчанию первый шаблон), Edit (TestVariantDTO, templateId? - по умолчанию старый шаблон варианта), которые используют BindToTemplate сервиса для обновления модели
- [ ] View соответствующие описанию задания
- List
- FormFields
- Edit
- Create

**Comment by ASbeletsky** [comment]
'Нужно ли помнить шаблон теста?'

Нет, каждый тест это создается по шаблону, копируя его состояние на текущий момент

**Comment by ASbeletsky** [comment]
> Нужно ли выводить в списке колонку с категориями и/или другие?

Ты про какой список?

**Comment by ASbeletsky** [comment]
> будет отдельная модель (TestResult ?), которая будет хранить ответы (id вопроса + ответ) 

Да, опять же, на момент создания теста будет скопирован правильный ответ на текущий момент

**Comment by Tirraon** [comment]
> Нет, каждый тест это создается по шаблону, копируя его состояние на текущий момент

Тогда как должно происходить редактирование?
Если мы не помним старый шаблон.

> Ты про какой список?

Список со всеми вариантами.
В таске с шаблонами был особый DTO для особого представления данных (вынести из уровней категории, форматировать вывод типов...)

**Comment by ASbeletsky** [comment]
> Тогда как должно происходить редактирование?

Можно запомнить шаблон при создании, а при редактировании, показывать задания те что были при создании теста + из шаблона, если поменялось из шаблона удалили уровень - показываем это уровень из теста, но помечаем красным, с сообщением что его уже не в шаблоне. Если уровень добавили в шаблон - тогда просто пустой уровень, обещательный для заполнения

**Comment by ASbeletsky** [comment]
> Список со всеми вариантами

Допишу позже

**Comment by Tirraon** [comment]
@ASbeletsky 
> - загловок "[Template Level Title] - [Template Level Count] tasks."

В TemplateLevel нет поля Title, проверил #8 - там тоже в задаче не былою

**Comment by ASbeletsky** [comment]
> В TemplateLevel нет поля Title

Ошибся, да, нужен Description

**Comment by Tirraon** [comment]
@ASbeletsky 
> Then: тесты представленны в виде таблицы с колонками:

Пока что я делаю в формате

| Template   | Variant         | Levels        | Actions|
| ------------- | ------------- | ------------- | ------------- |
| sample      | variant #99  | 1. 7 tasks  | Edit Delete|

Где sample  - заголовок шаблона
Где variant #99 - заголовок варианта
В Levels  список уровней с числом тасков в них

**Comment by ASbeletsky** [comment]
> Пока что я делаю в формате

Ok
