### ISSUE TITLE
Конфигурация тестирования

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/LMS#8]
**User story**: Студенты проходят тестирование в компании, путем ответа на воросы или решение задач, для подтверждение своих знаний и навыков. Необходимо автоматизировать этот процесс.

**Use case**: Модератор LMS задает конфигурацию теста для студентов.

When: Модератор заходит на страницу со списком доступных конфигураций тестов
Then: Конфигурации тестов представленны в виде таблицы с колонками:

- Name - имя теста;
- Categories - список категорий к которым относиться тест (через зяпятую в порядке убывания процента заданий с конкретной категорией);
- Avg. Сomplexity- средняя сложность заданий в тесте (двух символов после запятой);
- Tasks - список заданий в формате: level <номер уровня>: <тип задания> - <количество заданий такого типа>

When: Модератор нажимает на копку Create или Edit
Then: Отрывается страница с формой для создания/ редактирования теста. Форма содержит поля:

- Name - имя теста
- Description - описание (без гибкого форматирования)
- Duration - время, отведеное на выполнение теста  - timepicker
- Levels - список уровней теста. Каждый уровень имеет:
     - Description - поле для ввода (без гибкого форматирования);
     - Max score - поле для ввода цифр, максимальное количество баллов на этом уровне;
     - Tasks - список задач уровня с аттрибутами:
          - Categories - выпадающий список с категориями вопросов;
          - Types - выпадающий список с типами вопросов;
          - Complexity Range - slider с двумя ползунками (min and max complexity);
          - Score - поле для ввода с максимальным колличеством баллов за выполеное задание;
          - Count - поле для ввода с колличеством заданий на этом уровне;
          
When: Модератор нажимает на копку Details
Then: Отрывается readonly версия страницы Create / Edit

**Comment by Tirraon** [comment]
Колонка "Complexity" может лучше будет "Avg. complexity" или "Average complexity" в списке тестов?
Страница Details? Список полную информацию не предоставляет, к странице Edit (возможно) не у всех будет доступ.
Описание в данном случае будет без форматирования (говоря не о данной задаче, а вообще)?
Не совсем понял о:
> "Tasks - список задач уровня с аттрибутами: "

К чему тут выпадающие списки категорий, типов и слайдер?

Зачем вводить число заданий на этом уровне, если он может подсчитываться от реального числа связанных заданий?

**Comment by Tirraon** [comment]
Так же мы в категории и типе таски использовали Title для их наименований, не Name

**Comment by ASbeletsky** [comment]
> К чему тут выпадающие списки категорий, типов и слайдер?
> Зачем вводить число заданий на этом уровне, если он может подсчитываться от реального числа связанных заданий?

Конфигурации теста - это еще не сам тест, а его структура. Какие конкретно вопросы в нем будут на данном этапе не известны.

**Comment by Tirraon** [comment]
@ASbeletsky должна ли в конфигурации теста быть информация о его длительности?

**Comment by ASbeletsky** [comment]
> должна ли в конфигурации теста быть информация о его длительности?

да, обновил описание

**Comment by ASbeletsky** [comment]
> Level: Id, Description, MaxScore, Min/MaxComplexity, TestConfig + Id, TaskTypes (LevelTaskType), Categories (LevelCategory)

@Tirraon  где колличество заданий на уровне и Score каждого из них?
переименуй Level -> TestTemplateLevel 

> Min/MaxComplexity, TestConfig + Id, TaskTypes (LevelTaskType), Categories (LevelCategory)

я думаю их можно объеденить в сущность TaskFilter. Выносить в отдельную таблицу не стоит, но в c# можно выделить как property в сущности TestTemplateLevel. А на базу смапить с помощью https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities

> IUnitOfWork: TestConfigs, Levels

TestConfigs -> TestTemplate
Levels можно не добавлять в IUnitOfWork. С ними будем работать в рамках TestTemplate

> TestConfigDTO: Title, Id, Complexity, IReadOnlyList< CategoriesDTO>

Думаю для таблицы и для формы нужны разные dto, распиши оба

**Comment by Tirraon** [comment]
@ASbeletsky 
> где колличество заданий на уровне

Есть LevelDTO.Count для подсчета в бизнес логике валидных задач.
Но само количество задач в уровне не написал, о нем сразу не понял. Надо как-то название легко отличимое от числа валидных. Потом подумаю.

> Score каждого из них

MaxScore там есть. Поменял на Score, так как потребность в приставке "Max" не особо ясна.

> TaskFilter

Сделаю

> Levels можно не добавлять в IUnitOfWork. С ними будем работать в рамках TestTemplate

Предлагаете работать с уровнями через тот же репозиторий шаблонов тестов, который для этого расширить? Можно попробовать.

> Думаю для таблицы и для формы нужны разные dto, распиши оба

Нужно для того, чтобы в форму или таблицу не шли данные, которые там не используются?
Так то для уровней надо будет так же сделать.

**Comment by Tirraon** [comment]
@ASbeletsky 
может быть закрыто?

**Comment by Tirraon** [comment]
Azure опять игнорит бандл

**Comment by ASbeletsky** [comment]
@Tirraon пофикси проблему с скриптами и я закрою
